export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_USERNAME = 'SET_USERNAME';

export const LOGOUT = 'LOGOUT';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const DELETE_FAVOURITES = 'DELETE_FAVOURITES';
